-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ULTIMO PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ULTIMO PEDIDO` (
  `idULTIMO PEDIDO` INT NOT NULL,
  `Fecha_Entrega` DATE NULL,
  `Fecha_pedido` DATE NULL,
  `idCLIENTE` VARCHAR(45) NULL,
  `Trackorder` VARCHAR(45) NULL,
  `FACTURAS_idFACTURAS` INT NOT NULL,
  `FACTURAS_idCLIENTE` INT NOT NULL,
  `FACTURAS_idPROVEEDOR` INT NOT NULL,
  `FACTURAS_idTRANSPORTISTA` INT NOT NULL,
  `FACTURAS_idPRODUCTO` INT NOT NULL,
  PRIMARY KEY (`idULTIMO PEDIDO`, `FACTURAS_idFACTURAS`, `FACTURAS_idCLIENTE`, `FACTURAS_idPROVEEDOR`, `FACTURAS_idTRANSPORTISTA`, `FACTURAS_idPRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `CodigoPostal` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `País` VARCHAR(45) NULL,
  `Teléfono` VARCHAR(45) NULL,
  `email_cliente` VARCHAR(45) NULL,
  `Pedido_cliente` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  `Cliente_Premium` VARCHAR(45) NULL,
  `Método_Pago` VARCHAR(45) NULL,
  `idPEDIDO` VARCHAR(45) NULL,
  `ULTIMO PEDIDO_idULTIMO PEDIDO` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`, `ULTIMO PEDIDO_idULTIMO PEDIDO`),
  INDEX `fk_CLIENTE_ULTIMO PEDIDO1_idx` (`ULTIMO PEDIDO_idULTIMO PEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_ULTIMO PEDIDO1`
    FOREIGN KEY (`ULTIMO PEDIDO_idULTIMO PEDIDO`)
    REFERENCES `mydb`.`ULTIMO PEDIDO` (`idULTIMO PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `idPEDIDO` INT NOT NULL,
  `Trackorder` INT NULL,
  `idTRANSPORTISTA` VARCHAR(45) NULL,
  `Fecha_pedido` VARCHAR(45) NULL,
  `Fecha_Entrega` VARCHAR(45) NULL,
  `TRANSPORTISTA_idTRANSPORTISTA` INT NOT NULL,
  `id CLIENTE INT` INT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `idPRODUCTO` INT NULL,
  `CLIENTE_idCLIENTE1` INT NOT NULL,
  `CLIENTE_ULTIMO PEDIDO_idULTIMO PEDIDO` INT NOT NULL,
  PRIMARY KEY (`idPEDIDO`, `TRANSPORTISTA_idTRANSPORTISTA`, `CLIENTE_idCLIENTE`, `CLIENTE_idCLIENTE1`, `CLIENTE_ULTIMO PEDIDO_idULTIMO PEDIDO`),
  INDEX `fk_PEDIDO_CLIENTE_idx` (`CLIENTE_idCLIENTE` ASC, `idPRODUCTO` ASC) VISIBLE,
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_idCLIENTE1` ASC, `CLIENTE_ULTIMO PEDIDO_idULTIMO PEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE`
    FOREIGN KEY (`CLIENTE_idCLIENTE` , `idPRODUCTO`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE` , `idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE1` , `CLIENTE_ULTIMO PEDIDO_idULTIMO PEDIDO`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE` , `ULTIMO PEDIDO_idULTIMO PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `idPRODUCTO` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Categoría` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `AvgRate` VARCHAR(45) NULL,
  `idCLIENTE` INT NULL,
  `idPROVEEDOR` INT NOT NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` INT NOT NULL,
  `PEDIDO_CLIENTE_idCLIENTE` INT NOT NULL,
  `FACTURA_idFACTURAS` INT NOT NULL,
  `FACTURA_idCLIENTE` INT NOT NULL,
  `FACTURA_idPROVEEDOR` INT NOT NULL,
  `FACTURA_idTRANSPORTISTA` INT NOT NULL,
  `FACTURA_idPRODUCTO` INT NOT NULL,
  `FACTURA_idPEDIDO` INT NOT NULL,
  `FACTURA_PEDIDO_idPEDIDO` INT NOT NULL,
  `FACTURA_PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` INT NOT NULL,
  `FACTURA_PEDIDO_CLIENTE_idCLIENTE` INT NOT NULL,
  `FACTURA_PEDIDO_CLIENTE_idCLIENTE1` INT NOT NULL,
  `FACTURA_PEDIDO_CLIENTE_ULTIMO PEDIDO_idULTIMO PEDIDO` INT NOT NULL,
  PRIMARY KEY (`idPRODUCTO`, `idPROVEEDOR`, `FACTURA_idFACTURAS`, `FACTURA_idCLIENTE`, `FACTURA_idPROVEEDOR`, `FACTURA_idTRANSPORTISTA`, `FACTURA_idPRODUCTO`, `FACTURA_idPEDIDO`, `FACTURA_PEDIDO_idPEDIDO`, `FACTURA_PEDIDO_TRANSPORTISTA_idTRANSPORTISTA`, `FACTURA_PEDIDO_CLIENTE_idCLIENTE`, `FACTURA_PEDIDO_CLIENTE_idCLIENTE1`, `FACTURA_PEDIDO_CLIENTE_ULTIMO PEDIDO_idULTIMO PEDIDO`),
  INDEX `fk_PRODUCTO_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC, `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` ASC, `PEDIDO_CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO` , `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` , `PEDIDO_CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO` , `TRANSPORTISTA_idTRANSPORTISTA` , `CLIENTE_idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROVEEDOR` (
  `idPROVEEDOR` INT NOT NULL,
  `Departamento` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `CodigoPostal` INT NOT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `email_proveedor` VARCHAR(45) NULL,
  PRIMARY KEY (`idPROVEEDOR`, `CodigoPostal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE_copy1` (
  `idCLIENTE` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `CodigoPostal` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `País` VARCHAR(45) NULL,
  `Teléfono` VARCHAR(45) NULL,
  `email_cliente` VARCHAR(45) NULL,
  `Pedido_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO_PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO_PROVEEDOR` (
  `PRODUCTO_idPRODUCTO` INT NULL,
  `PROVEEDOR_idPROVEEDOR` INT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_PRODUCTO_has_PROVEEDOR_PROVEEDOR1_idx` (`PROVEEDOR_idPROVEEDOR` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_PROVEEDOR_PRODUCTO1_idx` (`PRODUCTO_idPRODUCTO` ASC, `PROVEEDOR_idPROVEEDOR` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_PRODUCTO_has_PROVEEDOR_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_idPRODUCTO` , `PROVEEDOR_idPROVEEDOR`)
    REFERENCES `mydb`.`PRODUCTO` (`idPRODUCTO` , `idPRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_PROVEEDOR_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_idPROVEEDOR`)
    REFERENCES `mydb`.`PROVEEDOR` (`idPROVEEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRANSPORTISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRANSPORTISTA` (
  `idTRANSPORTISTA` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `PROVEEDOR_idPROVEEDOR` INT NOT NULL,
  `PROVEEDOR_CodigoPostal` INT NOT NULL,
  PRIMARY KEY (`idTRANSPORTISTA`, `CodigoPostal`),
  INDEX `fk_TRANSPORTISTA_PROVEEDOR1_idx` (`PROVEEDOR_idPROVEEDOR` ASC, `PROVEEDOR_CodigoPostal` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSPORTISTA_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_idPROVEEDOR` , `PROVEEDOR_CodigoPostal`)
    REFERENCES `mydb`.`PROVEEDOR` (`idPROVEEDOR` , `CodigoPostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRANSPORTISTA_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRANSPORTISTA_PEDIDO` (
  `TRANSPORTISTA_idTRANSPORTISTA` INT NOT NULL,
  `TRANSPORTISTA_CodigoPostal` VARCHAR(45) NOT NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` INT NOT NULL,
  `PEDIDO_CLIENTE_idCLIENTE` INT NOT NULL,
  `IdTRANSPORTISTA_PEDIDO` INT NULL,
  PRIMARY KEY (`TRANSPORTISTA_idTRANSPORTISTA`, `TRANSPORTISTA_CodigoPostal`, `PEDIDO_idPEDIDO`, `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA`, `PEDIDO_CLIENTE_idCLIENTE`),
  INDEX `fk_TRANSPORTISTA_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC, `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` ASC, `PEDIDO_CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_TRANSPORTISTA_has_PEDIDO_TRANSPORTISTA1_idx` (`TRANSPORTISTA_idTRANSPORTISTA` ASC, `TRANSPORTISTA_CodigoPostal` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSPORTISTA_has_PEDIDO_TRANSPORTISTA1`
    FOREIGN KEY (`TRANSPORTISTA_idTRANSPORTISTA` , `TRANSPORTISTA_CodigoPostal`)
    REFERENCES `mydb`.`TRANSPORTISTA` (`idTRANSPORTISTA` , `CodigoPostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSPORTISTA_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO` , `PEDIDO_TRANSPORTISTA_idTRANSPORTISTA` , `PEDIDO_CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO` , `TRANSPORTISTA_idTRANSPORTISTA` , `CLIENTE_idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
